config-version: 2

name: 'gemma_dbt_utils'
version: '0.4.9'

require-dbt-version: ">=1.0.0"

profile: 'gemma_dbt_utils_profile'

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
log-path: "logs"
macro-paths: ["macros"]
model-paths: ["models"]

vars:
  # Variables related to the dim_dates model
  'gemma:dates:timezone': 'Europe/Berlin' # overwrite to get a different default value
  'gemma:dates:enabled': false # overwrite this variable to enable the date model
  'gemma:dates:start_date': '2020-01-01' # overwrite to get a different default value
  'gemma:dates:end_date': '30 day' # 30 days after the current date
  'gemma:dates:table': 'gemma_dates' # overwrite to get a different default value
  'gemma:dates:schema': 'gemma_dbt_utils' # overwrite to get a different default value

  # Variables related to the fx model
  'gemma:fx:currencies':
     EUR: 'gemma:fx:eur'  # define currency as other variables, or ...
     CHF: 'raw_fx.daily_fx_rates_usd_chf'  # ... name table directly
  # 'gemma:fx:eur': "{{ source('fx', 'eur') }}"  # must use this approach to use source macro
  'gemma:fx:enabled': false  # overwrite this variable to enable the fx model
  'gemma:fx:base_currency': 'USD' # overwrite to get a different default value

models:
  gemma_dbt_utils:
    # Defaults for all models in package
    +schema: gemma_dbt_utils
    +tags: gemma_dbt_utils
    +materialized: table
