config-version: 2

name: 'dbt_utils_integration_tests'
version: '1.0'

profile: 'integration_tests'

require-dbt-version: ">=1.0.0"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  # Set variables to configure the Gemma dbt utils package
  'gemma:dates:timezone': 'Europe/Berlin'
  'gemma:dates:enabled': true
  'gemma:dates:start_date': '2020-01-01'
  'gemma:dates:end_date': '30 day'
  'gemma:dates:table': 'gemma_dates'
  'gemma:dates:schema': 'gemma_dbt_utils'

  'gemma:fx:currencies':
    EUR: 'gemma:fx:eur'
    CHF: 'gemma:fx:chf'
  'gemma:fx:eur': "{{ source('fx', 'eur') }}"
  'gemma:fx:chf': "{{ source('fx', 'chf') }}"
  'gemma:fx:base_currency': EUR
  'gemma:fx:enabled': true
