config-version: 2

name: 'dbt_utils_integration_tests'
version: '1.0'

profile: 'integration_tests'

require-dbt-version: ">=0.17.0"

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"

vars:
  # Set variables to configure the Gemma dbt utils package
  'gemma:fx:currencies':
    EUR: 'gemma:fx:eur'
    CHF: 'gemma:fx:chf'
  'gemma:fx:eur': "{{ source('fx', 'eur') }}"
  'gemma:fx:chf': "{{ source('fx', 'chf') }}"
  'gemma:fx:base_currency': EUR
  'gemma:fx:enabled': true

  'gemma:ga4:enabled': true
  'gemma:ga4:source': "{{ source('bq', 'events') }}"
  'gemma:ga4:table': "raw_bq.events"
  'gemma:ga4:arrays':
    event_params:
      ga_session_id: BIGINT
      ga_session_number: INT
      engagement_time_msec: BIGINT
      gclid:
      campaign:
      content:
      medium:
      source:
      search_term:
      term:
      page_referrer:
      page_path:
      page_location:
      page_title:
      link_url:
      outbound: BOOLEAN
      session_engaged: BOOLEAN
      engaged_session_event: BOOLEAN
    user_properties:
      user_id:
      set_timestamp_micros: BIGINT
    # items: to be added..
