name: Release a new Gemma dbt utils version (GitHub tag)

on:
  push:  # only run on a merged PR to main
    branches:
      - master

jobs:
  build:
    name: Full Release Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies for GitHub release script
        run: |
          python -m pip install --upgrade pip
          pip install --upgrde pyyaml
      - name: Run new release Python script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # To authenticate POST
        run: python new_release.py
