version: 2

models:
  - name: gemma_fx
    description: "A model containing exchange rate data:
                  one row per date and currency."
    tests:
      - unique:
          column_name: concat(date, fx_currency)
    columns:
      - name: date
        description: The date that this row's exchange rate relates to.
        tests:
          - not_null
      - name: fx_currency
        description: The source currency relating to the row's exchange rate.
        tests:
          - not_null
      - name: base_currency
        description: The base currency relating to the row's exchange rate.
        tests:
          - not_null
      - name: fx_rate
        description: Multiply an amount in the source currency aka fx_currency
                     with the fx_rate to get an equivalent amount in the base
                     currency.
        tests:
          - not_null

  - name: gemma_ga4_events
    description: "A model containing Google Analytics 4 events.
                  Contains all fields but some nested from these there:
                  user_properties, event_params and items.
                  Explicit fields from those can be selected in the
                  projects YAML."
    columns:
      - name: event_id
        description: In the model created Id. Made out of the unique
                     combination of user_pseudo_id, event_timestamp,
                     event_name and event_params.
        tests:
          - unique
          - not_null

  - name: gemma_dates
    description: Date dimensional table. Creates a date series from a start_date
                 defined in the project until 30 days from now. Generates also
                 diverse date columns for a date like weekday, isoweek, etc.
    columns:
      - name: date_id
        description: Increasing Id from the first date in the table.
        tests:
          - unique
          - not_null
      - name: date
        tests:
          - unique
          - not_null
      - name: year
        description: Number of the year of the date.
      - name: iso_year
        description: ISO year of the date.
      - name: year_start
        description: First date of the year of the date.
      - name: quarter
        description: Number of the quarter of the date.
      - name: quarter_start
        description: First date of the quarter of the date.
      - name: month
        description: Number of the month of the date.
      - name: month_start
        description: First date of the month of the date.
      - name: week
        description: Number of the week of the date.
      - name: week_start
        description: First date of the week of the date.
      - name: iso_week
        description: Shows the ISO year and the ISO week number of the date.
      - name: iso_weekday
        description: Day of the ISO week, Monday = 1 to Sunday = 7.
      - name: weekday
        description: Day of the week, Sunday = 0 to Saturday = 6.
      - name: day
        description: Day of the month.
      - name: day_num
        description: Day of the year.
      - name: day_name
        description: First 3 letters of the written weekday name.
      - name: month_num
        description: Number of the month starting from first month in the table.
      - name: week_num
        description: Number of the week starting from first week in the table.
